package com.taskforge.service;

import com.taskforge.dto.request.TaskRequest;
import com.taskforge.dto.response.TaskResponse;
import com.taskforge.entity.Task;
import com.taskforge.enums.TaskPriority;
import com.taskforge.enums.TaskStatus;
import com.taskforge.exception.ResourceNotFoundException;
import com.taskforge.repository.TaskRepository;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * THE SERVICE LAYER — Where business logic lives.
 * ================================================
 *
 * WHY DO WE NEED A SERVICE?
 * In Module 2, our Controller did EVERYTHING:
 *   - Handled HTTP requests
 *   - Contained business logic
 *   - Stored/retrieved data
 *
 * That's bad because:
 *   1. The Controller becomes huge and unmaintainable
 *   2. Business logic can't be reused by other controllers
 *   3. Testing is harder (you have to test HTTP + logic together)
 *
 * The 3-Layer Architecture:
 * ┌──────────────────┐
 * │   Controller     │  ← Handles HTTP (request/response). Thin!
 * │   (Web Layer)    │     Only converts DTOs and calls Service.
 * ├──────────────────┤
 * │   Service        │  ← Business logic lives HERE.
 * │   (Business)     │     Validates, transforms, coordinates.
 * ├──────────────────┤
 * │   Repository     │  ← Database access. Just CRUD.
 * │   (Data Layer)   │     No business logic here.
 * └──────────────────┘
 *
 * @Service → tells Spring: "Create a Bean of this class and manage it."
 *           It's semantically the same as @Component, but signals
 *           "this is a service layer class" to other developers.
 *
 * DEPENDENCY INJECTION IN ACTION:
 * ──────────────────────────────
 * Look at the constructor below. It takes TaskRepository as a parameter.
 * Spring sees this and automatically provides the TaskRepository bean.
 * You don't write: new TaskService(new TaskRepository())
 * Spring does it for you. That's Dependency Injection!
 *
 * When there's only ONE constructor, Spring auto-injects without @Autowired.
 */
@Service
public class TaskService {

    private final TaskRepository taskRepository;

    // Constructor Injection — the RECOMMENDED way to inject dependencies.
    // Spring automatically provides the TaskRepository bean.
    //
    // Why "final"?
    //   - It makes the field immutable (can't be changed after construction)
    //   - Guarantees the repository is never null
    //   - This is a best practice for dependency injection
    public TaskService(TaskRepository taskRepository) {
        this.taskRepository = taskRepository;
    }

    // ====================================================================
    // GET ALL TASKS
    // ====================================================================
    /**
     * Fetches all tasks from the database and converts them to DTOs.
     *
     * Flow: Repository.findAll() → List<Task> → convert each → List<TaskResponse>
     *
     * .stream()   → converts the List to a Stream (for functional operations)
     * .map(...)   → transforms each Task entity → TaskResponse DTO
     * .toList()   → collects the results back into a List
     */
    public List<TaskResponse> getAllTasks() {
        return taskRepository.findAll()
                .stream()
                .map(this::mapToResponse)    // Convert each Task → TaskResponse
                .toList();
    }

    // ====================================================================
    // GET TASK BY ID
    // ====================================================================
    /**
     * Fetches a single task by its ID.
     *
     * taskRepository.findById(id) returns Optional<Task>:
     *   - If task exists → Optional containing the task
     *   - If not found   → Optional.empty()
     *
     * .orElseThrow() → if empty, throw our custom exception
     *                   which will later be caught and converted to HTTP 404
     */
    public TaskResponse getTaskById(Long id) {
        Task task = taskRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found with id: " + id));

        return mapToResponse(task);
    }

    // ====================================================================
    // CREATE TASK
    // ====================================================================
    /**
     * Creates a new task in the database.
     *
     * Flow:
     *   1. Convert TaskRequest DTO → Task entity
     *   2. Set defaults for null fields
     *   3. Save to database (taskRepository.save())
     *   4. Convert saved Task → TaskResponse DTO and return
     *
     * Note: We DON'T set id, createdAt, or updatedAt.
     *   - id        → auto-generated by @GeneratedValue
     *   - createdAt → auto-set by @CreationTimestamp
     *   - updatedAt → auto-set by @UpdateTimestamp
     */
    public TaskResponse createTask(TaskRequest request) {
        Task task = Task.builder()                        // Using the Builder pattern from Lombok!
                .title(request.title())
                .description(request.description())
                .status(request.status() != null ? request.status() : TaskStatus.TODO)
                .priority(request.priority() != null ? request.priority() : TaskPriority.MEDIUM)
                .build();

        Task savedTask = taskRepository.save(task);       // save() does INSERT INTO tasks (...)
        return mapToResponse(savedTask);
    }

    // ====================================================================
    // UPDATE TASK
    // ====================================================================
    /**
     * Updates an existing task.
     *
     * Flow:
     *   1. Find the existing task (throw 404 if not found)
     *   2. Update its fields from the request
     *   3. Save again (Hibernate detects it's an UPDATE, not INSERT,
     *      because the entity already has an ID)
     *   4. Return the updated task as a DTO
     */
    public TaskResponse updateTask(Long id, TaskRequest request) {
        Task existingTask = taskRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found with id: " + id));

        // Update the fields
        existingTask.setTitle(request.title());
        existingTask.setDescription(request.description());
        existingTask.setStatus(request.status());
        existingTask.setPriority(request.priority());
        // Note: createdAt stays unchanged (we never set it)
        //       updatedAt is automatically updated by @UpdateTimestamp

        Task updatedTask = taskRepository.save(existingTask);  // save() does UPDATE tasks SET ...
        return mapToResponse(updatedTask);
    }

    // ====================================================================
    // DELETE TASK
    // ====================================================================
    /**
     * Deletes a task by ID.
     *
     * We first check if the task exists. If not, throw 404.
     * Then we delete it using deleteById().
     *
     * Why check first instead of just calling deleteById()?
     *   deleteById() silently does nothing if the ID doesn't exist.
     *   We WANT to tell the client "that task doesn't exist" (404).
     */
    public void deleteTask(Long id) {
        if (!taskRepository.existsById(id)) {
            throw new ResourceNotFoundException("Task not found with id: " + id);
        }
        taskRepository.deleteById(id);  // DELETE FROM tasks WHERE id = ?
    }

    // ====================================================================
    // HELPER: Convert Task Entity → TaskResponse DTO
    // ====================================================================
    /**
     * This is a MAPPER method. It converts the internal database object (Entity)
     * to the external API object (DTO).
     *
     * Why not return the Entity directly?
     *   1. Security — Entity might have fields you don't want to expose
     *   2. Decoupling — if you change the Entity, the API response doesn't break
     *   3. Flexibility — response shape can differ from database shape
     *
     * In larger projects, you'd use a library like MapStruct to auto-generate
     * these mapper methods. For learning, we write them manually.
     */
    private TaskResponse mapToResponse(Task task) {
        return new TaskResponse(
                task.getId(),
                task.getTitle(),
                task.getDescription(),
                task.getStatus(),
                task.getPriority(),
                task.getCreatedAt(),
                task.getUpdatedAt()
        );
    }
}
